const employees = [
  {
    id: 1,
    firstName: "Ali",
    email: "ali@example.com",
    password: "123",
    taskNumber: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Design Login Page",
        taskDescription: "Create a responsive login page using React and Tailwind CSS.",
        taskDate: "2026-07-16",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix Navbar",
        taskDescription: "Resolve responsive issues in the navigation bar.",
        taskDate: "2026-07-14",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "API Integration",
        taskDescription: "Integrate login API with frontend.",
        taskDate: "2026-07-12",
        category: "Backend",
      },
    ],
  },

  {
    id: 2,
    firstName: "Ahmed",
    email: "jane.smith@example.com",
    password: "123",
    taskNumber: {
      active: 1,
      newTask: 0,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Dashboard UI",
        taskDescription: "Develop employee dashboard interface.",
        taskDate: "2026-07-16",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Profile Page",
        taskDescription: "Build user profile page.",
        taskDate: "2026-07-13",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Footer Component",
        taskDescription: "Create reusable footer component.",
        taskDate: "2026-07-11",
        category: "Component",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Dark Mode",
        taskDescription: "Implement dark mode functionality.",
        taskDate: "2026-07-10",
        category: "Feature",
      },
    ],
  },

  {
    id: 3,
    firstName: "Hassan",
    email: "michael.brown@example.com",
    password: "123",
    taskNumber: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create REST API",
        taskDescription: "Develop employee CRUD API.",
        taskDate: "2026-07-16",
        category: "Backend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "JWT Authentication",
        taskDescription: "Implement JWT authentication.",
        taskDate: "2026-07-17",
        category: "Security",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Database Schema",
        taskDescription: "Create MySQL database schema.",
        taskDate: "2026-07-12",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Error Handling",
        taskDescription: "Improve API error responses.",
        taskDate: "2026-07-11",
        category: "Backend",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Redis Cache",
        taskDescription: "Implement Redis caching.",
        taskDate: "2026-07-09",
        category: "Performance",
      },
    ],
  },

  {
    id: 4,
    firstName: "Usman",
    email: "emily.johnson@example.com",
    password: "123",
    taskNumber: {
      active: 2,
      newTask: 1,
      completed: 3,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Write Test Cases",
        taskDescription: "Create unit tests for login module.",
        taskDate: "2026-07-16",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Bug Verification",
        taskDescription: "Verify reported UI bugs.",
        taskDate: "2026-07-14",
        category: "QA",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Regression Testing",
        taskDescription: "Perform regression testing.",
        taskDate: "2026-07-12",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Performance Test",
        taskDescription: "Run load tests on server.",
        taskDate: "2026-07-10",
        category: "Performance",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Automation Script",
        taskDescription: "Create Selenium automation scripts.",
        taskDate: "2026-07-18",
        category: "Automation",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Test Documentation",
        taskDescription: "Update QA documentation.",
        taskDate: "2026-07-08",
        category: "Documentation",
      },
    ],
  },

  {
    id: 5,
    firstName: "Bilal",
    email: "david.wilson@example.com",
    password: "123",
    taskNumber: {
      active: 3,
      newTask: 1,
      completed: 3,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Deploy Website",
        taskDescription: "Deploy React application to production.",
        taskDate: "2026-07-16",
        category: "DevOps",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "CI/CD Pipeline",
        taskDescription: "Configure GitHub Actions pipeline.",
        taskDate: "2026-07-17",
        category: "DevOps",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Docker Setup",
        taskDescription: "Containerize application using Docker.",
        taskDate: "2026-07-13",
        category: "DevOps",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Server Backup",
        taskDescription: "Configure automatic server backups.",
        taskDate: "2026-07-11",
        category: "Infrastructure",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Kubernetes Setup",
        taskDescription: "Deploy application to Kubernetes cluster.",
        taskDate: "2026-07-09",
        category: "Cloud",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "SSL Configuration",
        taskDescription: "Configure SSL certificates for production.",
        taskDate: "2026-07-18",
        category: "Security",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Nginx Configuration",
        taskDescription: "Optimize Nginx server settings.",
        taskDate: "2026-07-07",
        category: "Server",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
    localStorage.setItem("employees",JSON.stringify(employees));
    localStorage.setItem("admin",JSON.stringify(admin));
}

export const getLocalStorage = () => {
    const employees = JSON.parse(localStorage.getItem("employees"));    
    const admin = JSON.parse(localStorage.getItem("admin"));   
    
    return {employees, admin};
}